### PR TITLE
[view] bind events to array of commands

### LINKED ISSUE #29: bind events to array of commands

### PR DESCRIPTION
**Pull request by gohryt**
Closes #29

### CODE REVIEW

**Comment by xania** [comment]
@gohryt overrall useful structural changes I agree with or don't mind following, but behavioral changes need to be verified, especially setTimeout change to new Promise without a specific delay, and the default value for link as root does not make sense to me. Could you provide arguments for why this is a good default?

**Comment by gohryt** [comment]
Hello, it's not a final version, i will tag you when finish.
I am currently trying to fix #30 router issue and all changes i made is experimental on my way.
My goal is supporting both absolute and relative "to" targets as in classical "href".

**Comment by gohryt** [comment]
@xania please check it, seems like it's currently working in project i shared before (github.com/rays-of-good/peacedalove.com), but not in netlify preview app and i can't understand why.

**Comment by gohryt** [comment]
@xania hello! Seems like it's not perfect but working now (#30). I tested it with spa i shared in this issue before and all good. I made some style changes but most important changes is in link component. It now should work as absolute and relative unix paths ("/something", "./something"|"something", "../something") so seems like this issue is done. Wil be happy with your review.

**Comment by gohryt** [comment]
So?

**Comment by ibrahimbensalah** [comment]
@gohryt apology for the delay, was busy relocating, started new project and holidays all at once, I still need to free up some time for the time being I will merge and public this PR. and will solve whatever comes up later myself

**Pull request merged**
